"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = "[>](bold purple)"
error_symbol = "[✗](bold red)"

[package]
disabled = true

[git_branch]
symbol = "🌱 "

[nodejs]
symbol = "⬢ "
